// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otwqqfqkndhpuomkrzdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90d3FxZnFrbmRocHVvbWtyemR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3OTYyMDksImV4cCI6MjA1NDM3MjIwOX0.mQK9qujPLCMCLesCU_oPKIbBTT3qILNBAoifA3rSAKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);